language: node_js
node_js:
  - 12
addons:
  apt:
    packages:
      - libgconf-2-4
cache: npm
install:
  - npm install --ignore-scripts
  - npm rebuild puppeteer
script:
  - npm run test-report-coverage