import { createURL } from "@mationbot/helpers/urls"

import { ROOT_ASSETS_DIRECTORY, ASSETS_SCREENSHOTS_DIRECTORY } from "@config"

/**
 * @description   Provides functions in dealing with assets generated by the script ie page screenshots
 */

/**
 * @param fileName file name with extension without preceding backlash
 * @return  string   relative to script root directory, the url to a page screenshot asset (file)
 * @example  getPageScreenshotLocalFileUrl('photo.png') => 'assets/screenshots/pages/photo.png'
 */
export const getScreenshotLocalFilePath = (fileName: string): string => 
  createURL('.', ROOT_ASSETS_DIRECTORY, ASSETS_SCREENSHOTS_DIRECTORY) + fileName
