import { createURL } from "@mationbot/helpers/urls"

/**
 * @description   Provides functions in dealing with assets generated by the script ie page screenshots
 */

// Configure
const ASSETS_FOLDER = 'assets'
const ASSETS_SCREENSHOTS_FOLDER = 'screenshots'
const ASSETS_SCREENSHOTS_PAGES_FOLDER = 'pages'

/**
 * @param fileName file name with extension without preceding backlash
 * @return  string   relative to script root directory, the url to a page screenshot asset (file)
 * @example  getPageScreenshotLocalFileUrl('photo.png') => 'assets/screenshots/pages/photo.png'
 */
export const getPageScreenshotLocalFileUrl = (fileName: string): string => 
  createURL(ASSETS_FOLDER, ASSETS_SCREENSHOTS_FOLDER, ASSETS_SCREENSHOTS_PAGES_FOLDER) + fileName